### ISSUE TITLE
Python版本和IDE工具咨询

### ISSUE THREAD

**Issue by xiaoxiaoyao** [tanteng/learn-python#1]
Tony，
您好。
1. 我想了解您具体使用的Python是哪个版本，是Python3.5.1吗？还是其他版本？非常感谢O(∩_∩)O。
2. 另外想问一下，您用的IDE是哪个工具？

**Comment by tanteng** [comment]
IDE是PyCharm4.5，Python版本是3.4.3

**Comment by xiaoxiaoyao** [comment]
好的，我提交了一个readme的pull request，帮忙同意一下o(^▽^)o。另外记得close掉这个issue。非常感谢。
